### ISSUE TITLE
Pomodoro Timer bugs 

### ISSUE THREAD

**Issue by maverick4200** [wtvamp/PomodoroTimerPlugin#4]
1. If the user starts the timer and resets the timer the stop and reset buttons are greyed out but the start button is still clickable. If the user clicks the start button the timer resets and the counters rate increases. at this time the user is not able to pause or reset the timer. if the user constantly presses the start and reset buttons the counters rate will increase. Once the timer finishes and the user decides to reset the timer the text in the center stays red even if the user presses the reset or stop button.

2. Sometimes if the user presses the start button and then presses the reset button the counters rate increases, sometimes it doesn't... The stop button also lost its functionality when the user clicked the start button, reset button and, the start button again.

**Comment by wtvamp** [comment]
This is resolved in version 0.4.0-beta
